name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install

      - name: Build
        run: npm run build-lib

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./dist/ngx-jdenticon.tgz
